apiVersion: skaffold/v4beta1
kind: Config
build:
  googleCloudBuild:
    projectId: crypto-minutia-426422-g1
  artifacts:
    - image: us.gcr.io/crypto-minutia-426422-g1/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - ./infra/k8s/*
